### ISSUE TITLE
Additional classes (Location, Event)

### ISSUE THREAD

**Issue by jpmckinney** [influencemapping/whos_got_dirt-gem#16]
In addition to Entity, Relation, and List, some workshop people where interested in Location and Event. Let's wait to see how common these classes are across APIs (and whether they are treated as first-level classes).

**Comment by miguelpaz** [comment]
Can you remind me what "Event" stands for James? I recall Chris using it
but not the context

**Comment by jpmckinney** [comment]
I don't remember how Chris used it, but some people mentioned, for example, politically exposed people attending the same event (lunch, fundraiser, meeting, conference, etc.)

**Comment by miguelpaz** [comment]
Oh just good ol` events. Get it. Yes.


2015-10-16 13:47 GMT-03:00 James McKinney <notifications@github.com>:

> I don't remember how Chris used it, but some people mentioned, for
> example, politically exposed people attending the same event (lunch,
> fundraiser, meeting, conference, etc.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/influencemapping/whos_got_dirt-gem/issues/16#issuecomment-148765715>
> .
>



-- 
Miguel Paz @miguelpaz
Nieman-Berkman Fellow 2014-2015
Poderomedia.org @poderomedia - Poderopedia.org @poderopedia
PoderomediaAcademy #PAcademy - Manual Periodismo de Datos @periodismodata
Hacks/Hackers Chile @hackshackersSCL

**Comment by jpmckinney** [comment]
Noting that I haven't found any APIs yet that make these searchable endpoints.

**Comment by jpmckinney** [comment]
Can be reopened if we discover any APIs that have endpoints for searching these data types.
