### ISSUE TITLE
EveryPolitician compilation

### ISSUE THREAD

**Issue by jpmckinney** [influencemapping/whos_got_dirt-gem#21]
Auto-generate compilations of EveryPolitician data on Heroku.
1. Subscribe to a hook on EveryPolitician to be notified any time there's a data change
2. Iterate through the legislatures
3. Build a master `names` file and/or `terms` file
4. Store it somewhere (e.g. in a GitHub Pages repo)

For this, https://github.com/everypolitician/everypolitician-writeinpublic is a good template.

**Comment by davewhiteland** [comment]
Hi @jpmckinney heads up that as part of the job of documenting the way we support this, I'm going to be attempting to knock such a thing together; working on it now

**Comment by jpmckinney** [comment]
I had thrown something together at https://github.com/influencemapping/whos_got_dirt-json_file_api but it's search mechanism is terrible: https://github.com/influencemapping/whos_got_dirt-json_file_api/issues/1

**Comment by jpmckinney** [comment]
Oops, sorry, I thought this was a different issue! Nevermind.

**Comment by davewhiteland** [comment]
A `names.csv` exists for you now, @jpmckinney 

https://everypolitician.github.io/everypolitician-names/names.csv (warning: big file!) is being regenerated whenever EveryPolitician data changes.

Under the hood: https://github.com/everypolitician/everypolitician-names is making that file in its own `gh_pages` branch, subscribed to EveryPolitician's "hey-data-has-changed" webhook.

**Comment by jpmckinney** [comment]
Awesome, thanks!

**Comment by jpmckinney** [comment]
Done. Adding API handlers for EveryPolitician is covered in #3.
